### ISSUE TITLE
not paused when saving

### ISSUE THREAD

**Issue by stsp** [oitofelix/mininim#10]
When you press Ctrl-g, game is not paused.
While you select the file to save, the guard can
come close and you save in a very bad position.
All games I know of, freeze during the save dialog.

Btw, how is to restore?

**Comment by oitofelix** [comment]
Indeed, the game should pause while saving.  However, the game save feature is not of the "save state" kind.  Like in the original game, it only stores the level, remaining time, total life points, and skills (MININIM specific).

You can restore the save using CTRL+L.  Use it in the title screen (like in the original game), or load anytime and restart the game (CTRL+R).

**Comment by oitofelix** [comment]
Thanks for reporting!
