### ISSUE TITLE
Debian sid build

### ISSUE THREAD

**Issue by int-0** [oitofelix/mininim#11]
Hi!
I'm trying to build your program in my Debian and I have a problem with "./configure":

> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for ALLEGRO... no
> configure: error: MININIM requires Allegro 5.0.9 (or superior)

Allegro is installed (obviously) the problem is the name in pkg-config: in Debian sid is "allegro-5" instead of "allegro-5.0":

> tobias@ontable:~/Games/mininim/mininim-0.10$ pkg-config --list-all | grep allegro | sort
> allegro-5                        allegro - Allegro game programming library
> allegro_acodec-5                 allegro_acodec - Allegro game programming library, audio codec addon
> allegro_audio-5                  allegro_audio - Allegro game programming library, audio addon
> allegro_color-5                  allegro_color - Allegro game programming library, colors addon
> allegro_dialog-5                 allegro_dialog - Allegro game programming library, native dialog addon
> allegro_font-5                   allegro_font - Allegro game programming library, font addon
> allegro_image-5                  allegro_image - Allegro game programming library, image I/O addon
> allegro_main-5                   allegro_main - Allegro game programming library, magic main addon
> allegro_memfile-5                allegro_memfile - Allegro game programming library, memory files addon
> allegro_physfs-5                 allegro_physfs - Allegro game programming library, PhysicsFS addon
> allegro_primitives-5             allegro_primitives - Allegro game programming library, primitives addon
> allegro_ttf-5                    allegro_ttf - Allegro game programming library, TrueType fonts addon
> allegro_video-5                  allegro_video - Allegro game programming library, video player addon

bye!

**Comment by oitofelix** [comment]
Hello!

Please, try commit 4a11fb4.

**Comment by int-0** [comment]
Now works nice!

**Comment by oitofelix** [comment]
Thanks for reporting.  Have fun!
