### ISSUE TITLE
Cannot execute

### ISSUE THREAD

**Issue by int-0** [oitofelix/mininim#12]
Hi,
After build I get this error when I try to execute the program:

> ./mininim: create_bitmap (320, 200): cannot create bitmap

Using "al_get_errno()" in the code I get the value "0x02" but I don't know what it means :(

I don't know how to get more information about this issue to help you, if you have an idea, I'm happy to help you with this awesome project... ;)

**Comment by oitofelix** [comment]
Hello,

Please, post here the output of 'uname -a' and the configuration options you've passed to the configure script.

Obtaining a backtrace would be quite useful.  For this reconfigure MININIM with the `--enable-debug` option, then debug the program in gdb: `gdb mininim`.  Insert a breakpoint in the line that calls the error function: `br video.c:144` (check the line number as it might be different for you), and then run the program: `r`.  When the execution reaches the break point, get the backtrace: `bt`, and post it here.

Thank you for reporting and willing to help me sort this problem out.

Ps: if you have any problems or questions, don't hesitate to post them here.

**Comment by int-0** [comment]
Hi,
Np... I like to contribute to this awesome project :D
Ok... my system:

> tobias@ontable:~/dev/repos/mininim$ uname -a
> Linux ontable 4.5.0-2-amd64 #1 SMP Debian 4.5.3-2 (2016-05-08) x86_64 GNU/Linux
> tobias@ontable:~/dev/repos/mininim$ glxinfo 
> name of display: :0
> display: :0  screen: 0
> direct rendering: Yes
> server glx vendor string: SGI
> server glx version string: 1.4
> ...
> Extended renderer info (GLX_MESA_query_renderer):
>     Vendor: X.Org (0x1002)
>     Device: AMD RV620 (DRM 2.43.0, LLVM 3.7.1) (0x95c5)
>     Version: 11.1.3
>     Accelerated: yes
>     Video memory: 256MB
>     Unified memory: no
>     Preferred profile: core (0x1)
>     Max core profile version: 3.3
>     Max compat profile version: 3.0
>     Max GLES1 profile version: 1.1
>     Max GLES[23] profile version: 3.0
> OpenGL vendor string: X.Org
> OpenGL renderer string: Gallium 0.4 on AMD RV620 (DRM 2.43.0, LLVM 3.7.1)
> OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.3
> OpenGL core profile shading language version string: 3.30
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> ...
> tobias@ontable:~/dev/repos/mininim$ dpkg -l liballegro5-dev
> Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
> | Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
> |/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
> ||/ Nombre               Versión         Arquitectura    Descripción
> +++-====================-===============-===============-=============================================
> ii  liballegro5-dev:amd6 2:5.2.0-1       amd64           development files for the Allegro 5 library

I ran "./configure --enable-debug" (and without debug of course) an then "make". Compilation runs perfect (without warnings... nice job!) and then I ran "./mininim".

I'll try to debug the program but I don't have very much free time...

**Comment by oitofelix** [comment]
I see you are running Allegro 5.2.0.  MININIM is developed against 5.0.10.  I'll try to build and test against that version.

Please, try running MININIM with the option `--multi-room=1x1`, and then `--display-mode=0`.

**Comment by oitofelix** [comment]
Yeah, with Allegro 5.2.0 I get the same error as you.  Neither of those options work.  I'll try to figure this out soon and get back to you.

**Comment by oitofelix** [comment]
Please, try commit 935c95e.

**Comment by int-0** [comment]
Wuoa! now it works! thank you!

**Comment by oitofelix** [comment]
Welcome!  Please, let me know about any other problem you happen to find out along the way.

**Comment by vasisualiy** [comment]
Please, reopen. Allegro version 5.2.2. The same problem here.
