### ISSUE TITLE
Seg fault.

### ISSUE THREAD

**Issue by Achaean** [oitofelix/mininim#13]
**Hi!** :-)

Running the game with the --start-time=N switch (eg. mininim --start-time=7200), do the game to start and playing the introduction, but when pressing Enter the game starts but returns a segmentation fault and aborts.

I'm on Mint 17.3 x64 KDE and i installed the 0.10 version from homepage.

Bye! :-)
G.

**Comment by oitofelix** [comment]
Hello,

This bug has been fixed in the development version already.

Thanks for reporting.

**Comment by Achaean** [comment]
**THANKS** Bruno! :-)

I tried installing the development version and I had a problem.
Since it is not related to this bug, I posted at forum instead.

Thanks again and keep up the good work!!!
G. :-)
