### ISSUE TITLE
sword doesn't work

### ISSUE THREAD

**Issue by stsp** [oitofelix/mininim#8]
In original game, the sword is taken on-guard
automatically when the guard is seen. But minimim
doesn't take the sword out, so guard just kills me.

**Comment by oitofelix** [comment]
That's an intended feature.  You can draw the sword pressing ENTER, after you get it.  MININIM's battle system is quite different from the original.  Please refer to its manual (section 2.8 "Fight" in version 0.9.2) to find out how.

**Comment by stsp** [comment]
Well, 2.8 seems to describe the battle system,
but it doesn't seem to be saying what is the difference
with the original and why. So I still don't know why
is this a feature. Maybe it is possible to invent the
optional compatibility mode, which will match the
original with 100% accuracy?

**Comment by oitofelix** [comment]
In fact, it briefly states in the footnotes.  It doesn't give a rationale of why its way is better, though.
It's not an aim of MININIM to match the original, where we can do better.

**Comment by stsp** [comment]
OK, the footnotes indeed list a new features,
including this one. While I can see why some
new moves may be considered an improvement,
having to press Enter to take out a sword, doesn't
look like the one. So maybe you should at least
explain it better in the docs, or make optional.
See, while all other features are just add-ons,
this one is a real gotcha, as it makes the player
to be immediately killed where previously he
would successfully fight. This means every player
have to carefully study the manual before he
could barely play! IMHO this is quite nasty addition.
Anyway, feel free to close this.

**Comment by oitofelix** [comment]
People have asked me about this before, here is the answer I gave:

http://forum.princed.org/viewtopic.php?f=69&t=3783#p18210
